### ISSUE TITLE
Thrown error exits app

### ISSUE THREAD

**Issue by thetoxicavenger** [kesla/jade-to-handlebars#5]
➜  views git:(master) ✗ jade-to-handlebars layout.jade

``` javascript
/usr/local/lib/node_modules/jade-to-handlebars/lib/walk.js:69
  throw new Error(
        ^
Error: Unsupported node, type Extends in gallery.jade
    at walk (/usr/local/lib/node_modules/jade-to-handlebars/lib/walk.js:69:9)
    at Array.map (native)
    at walk (/usr/local/lib/node_modules/jade-to-handlebars/lib/walk.js:12:22)
    at module.exports (/usr/local/lib/node_modules/jade-to-handlebars/index.js:10:14)
    at /usr/local/lib/node_modules/jade-to-handlebars/bin/jade-to-handlebars.js:11:20
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/jade-to-handlebars/bin/jade-to-handlebars.js:8:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

I'm assuming the "Extends" keyword is the problem, given the error message. Below is the gallery.jade text that the error is referencing:

``` jade
// 438 px width for each photo on my display.
// * Add more MQ's for bigger screens.
// ** Need to add second set of full-res photos to ajax request for lightbox; make each img an a element.

extends layout

block content

    h1.caviarDreams-font#theH1(style="margin-top: 20px; font-size: 65px;")

    .photos-container#photosContainer

    script(type="text/javascript", src="/js/photos.js")
```

**Comment by kesla** [comment]
@thetoxicavenger thanks for the bug, looking at it now. Sorry for the delay, been traveling.

**Comment by thetoxicavenger** [comment]
Thank you! Not sure if I'm going to continue with handlebars or not, but I
appreciate your diligence.
- Mitch
